server:
  port: 8081
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
redis:
  hostname: localhost
  port: 6379
  password: root